package com.example.imiq

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.runtime.staticCompositionLocalOf

// =====================================================================
//  Lightweight in-app localization (EN / DE).
//  - Type-safe: every string is a field on [Strings], so a missing
//    translation is a compile error, not a demo-time crash.
//  - Runtime switch: [LanguageState.current] is Compose state, so flipping
//    the language recomposes the whole app instantly (no Activity restart).
//  - Composables read LocalStrings.current; plain code reads appStrings().
// =====================================================================

enum class AppLanguage(val code: String) { EN("en"), DE("de") }

/** Reactive, persisted app language. Read in composition via LocalStrings. */
object LanguageState {
    var current by mutableStateOf(AppLanguage.EN)
        private set

    /** Restore the saved language (call once after TokenManager.init). */
    fun init() {
        current = if (TokenManager.getLanguage() == AppLanguage.DE.code) AppLanguage.DE else AppLanguage.EN
    }

    fun set(lang: AppLanguage) {
        current = lang
        TokenManager.setLanguage(lang.code)
    }
}

/** The active string table for non-composable code (DemoRoutingData, services). */
fun appStrings(): Strings = if (LanguageState.current == AppLanguage.DE) DeStrings else EnStrings

/** Provided at the app root; composables read LocalStrings.current. */
val LocalStrings = staticCompositionLocalOf { EnStrings }

// ---------------------------------------------------------------------
//  The string table. Strings with %s / %d are used with String.format.
// ---------------------------------------------------------------------
data class Strings(
    // -- Common --
    val back: String,
    val cancel: String,
    // -- Splash --
    val splashTagline: String,
    // -- Sign up --
    val signupTagline: String,
    val accessCode: String,
    val getStarted: String,
    val noCodePrefix: String,
    val registerHere: String,
    // -- Home --
    val goodMorning: String,
    val goodAfternoon: String,
    val goodEvening: String,
    val whereHeaded: String,
    val whereTo: String,
    val smart: String,
    val savedRecent: String,
    val personalizedRouting: String,
    val rankedByPassport: String,
    val searchPlaceMd: String,
    val popularInMd: String,
    val searching: String,
    val noPlacesFound: String,      // %s = query
    val savedHome: String,
    val savedCampus: String,
    // -- Route results --
    val yourLocation: String,
    val aiRecommendation: String,
    val chooseHowToGo: String,
    val aiPick: String,
    val match: String,
    val analyzing: String,
    val start: String,
    val bestMatch: String,          // %s = mode
    val topsRanking: String,        // %s = value list
    val rankedHighest: String,
    val bestForNow: String,         // %s = mode
    val directionsTitle: String,
    val openInMaps: String,
    // -- Settings --
    val settings: String,
    val bikeLeaningProfile: String,
    val generalSection: String,
    val language: String,
    val languageSub: String,
    val routingPreferences: String,
    val prefEcoTitle: String,
    val prefEcoSub: String,
    val prefUnlitTitle: String,
    val prefUnlitSub: String,
    val prefLiveTitle: String,
    val prefLiveSub: String,
    val profileSection: String,
    val recreateProfile: String,
    val recreateProfileSub: String,
    val resetRecreate: String,
    val aboutSection: String,
    val aboutBlurb: String,
    val resetDialogTitle: String,
    val resetDialogBody: String,
    val reset: String,
    // -- Onboarding: step titles --
    val stepWelcome: String,
    val stepNeeds: String,
    val stepPriorities: String,
    val stepBeliefs: String,
    val stepFrequencies: String,
    val stepEmoval: String,
    val stepGenerating: String,
    val stepResult: String,
    val stepXofY: String,           // %d, %d
    // -- Onboarding: welcome --
    val welcomeHeadline: String,
    val welcomeBody: String,
    val welcomeInfo1: String,
    val welcomeInfo2: String,
    val welcomeInfo3: String,
    val welcomeInfo4: String,
    val welcomeInfo5: String,
    // -- Onboarding: needs --
    val needsIntro: String,
    val needsScaleHint: String,
    // -- Onboarding: priorities --
    val prioritiesIntro: String,
    val prioritiesTapHint: String,
    val empty: String,
    val ratingLabel: String,        // %d
    // -- Onboarding: beliefs --
    val beliefsIntro: String,
    val beliefsScaleHint: String,
    val beliefsPickFirst: String,
    val neverUse: String,
    val mostImportantNeed: String,
    // -- Onboarding: frequencies --
    val frequenciesIntro: String,
    val frequenciesScaleHint: String,
    // -- Onboarding: emoval --
    val emovalIntro: String,
    val emovalHint: String,
    val negative: String,
    val positive: String,
    val noExperience: String,
    // -- Onboarding: generating --
    val genStage1: String,
    val genStage2: String,
    val genStage3: String,
    val genStage4: String,
    val genStage5: String,
    val genStage6: String,
    val generatingServer: String,
    val genErrTitle: String,
    val genErrHelp: String,
    val tryAgain: String,
    val useOffline: String,
    // -- Onboarding: result --
    val resultReady: String,
    val resultSubtitle: String,
    val travelPersonality: String,
    val readingProfile: String,
    val resultTailored: String,
    // -- Onboarding: bottom bar --
    val letsBegin: String,
    val nextBtn: String,
    val generatePassport: String,
    val continueToApp: String,
    // -- Passport detail --
    val cognitivePassportTitle: String,
    val noPassportTitle: String,
    val noPassportSub: String,
    val pdMetadata: String,
    val pdMetadataSub: String,
    val pdProfile: String,
    val pdProfileSub: String,
    val pdDeliberation: String,
    val pdDeliberationSub: String,
    val pdDissonance: String,
    val pdDissonanceSub: String,
    val pdRouting: String,
    val pdRoutingSub: String,
    val pdXai: String,
    val pdXaiSub: String,
    val pdAgent: String,
    val pdSpatial: String,
    val pdSpatialSub: String,
    val pdTopNeeds: String,
    val pdRawJson: String,
    val pdRawJsonSub: String,
    // -- Keyed lookups (by stable code keys) --
    val needLabels: Map<String, String>,
    val needHelps: Map<String, String>,
    val onbModeLabels: Map<String, String>,   // walk/bike/pt/car (long)
    val modeLabels: Map<String, String>,      // bike/car/foot/walk/pt (short)
    val valueLabels: Map<String, String>,     // dimension -> chip label
)

// ---------------------------------------------------------------------
//  English
// ---------------------------------------------------------------------
val EnStrings = Strings(
    back = "Back",
    cancel = "Cancel",
    splashTagline = "Smart mobility, personalized",
    signupTagline = "Personalized smart routing for Magdeburg",
    accessCode = "Access code",
    getStarted = "Get started",
    noCodePrefix = "Don't have a code? ",
    registerHere = "Register here",
    goodMorning = "Good morning",
    goodAfternoon = "Good afternoon",
    goodEvening = "Good evening",
    whereHeaded = "Where are you headed?",
    whereTo = "Where to?",
    smart = "Smart",
    savedRecent = "SAVED & RECENT",
    personalizedRouting = "Personalized routing",
    rankedByPassport = "Ranked by your cognitive passport",
    searchPlaceMd = "Search a place in Magdeburg",
    popularInMd = "POPULAR IN MAGDEBURG",
    searching = "Searching…",
    noPlacesFound = "No places found in Magdeburg for \"%s\".",
    savedHome = "Home",
    savedCampus = "Campus",
    yourLocation = "Your location",
    aiRecommendation = "AI RECOMMENDATION",
    chooseHowToGo = "CHOOSE HOW TO GO",
    aiPick = "AI PICK",
    match = "match",
    analyzing = "Analyzing live traffic, weather & your passport…",
    start = "Start",
    bestMatch = "%s is your best match",
    topsRanking = "Tops your ranking — strong on %s for your profile.",
    rankedHighest = "Ranked highest for your cognitive passport.",
    bestForNow = "%s — best for right now",
    directionsTitle = "Directions",
    openInMaps = "Open in Google Maps",
    settings = "Settings",
    bikeLeaningProfile = "BIKE-leaning profile",
    generalSection = "GENERAL",
    language = "Language",
    languageSub = "App language",
    routingPreferences = "ROUTING PREFERENCES",
    prefEcoTitle = "Prefer eco-friendly routes",
    prefEcoSub = "Bias toward low-emission modes",
    prefUnlitTitle = "Avoid unlit paths at night",
    prefUnlitSub = "Safer routing after dark",
    prefLiveTitle = "Use live traffic & weather",
    prefLiveSub = "Adapt recommendations in real time",
    profileSection = "PROFILE",
    recreateProfile = "Recreate profile",
    recreateProfileSub = "Redo onboarding to rebuild your cognitive passport",
    resetRecreate = "Reset & recreate",
    aboutSection = "ABOUT",
    aboutBlurb = "Personalized urban mobility for Magdeburg — routes ranked by your cognitive passport and live city data.",
    resetDialogTitle = "Reset profile?",
    resetDialogBody = "This clears your cognitive passport and runs the onboarding questions again to regenerate it.",
    reset = "Reset",
    stepWelcome = "Welcome",
    stepNeeds = "Your mobility needs",
    stepPriorities = "Your top 3 priorities",
    stepBeliefs = "Suitability of transport modes",
    stepFrequencies = "How you get around",
    stepEmoval = "How modes feel to you",
    stepGenerating = "Building your passport",
    stepResult = "Your cognitive passport",
    stepXofY = "Step %d of %d",
    welcomeHeadline = "Let's get to know your travel mind",
    welcomeBody = "A short 5-part questionnaire. Takes about 4 minutes. We'll then generate your personal cognitive passport — a map of how you weigh different mobility needs.",
    welcomeInfo1 = "Rate 11 mobility needs (1–7)",
    welcomeInfo2 = "Pick your top 3 priorities",
    welcomeInfo3 = "Rate how well modes fit your needs",
    welcomeInfo4 = "Tell us how often you use each mode",
    welcomeInfo5 = "Share how each mode feels to you",
    needsIntro = "How important are each of these to you personally when you choose a transport mode?",
    needsScaleHint = "1 = not at all important, 7 = extremely important",
    prioritiesIntro = "We can't always have everything at once. From the list, pick the 3 most important needs for your transport choices, in order.",
    prioritiesTapHint = "Tap a need below to add it to your pyramid:",
    empty = "empty",
    ratingLabel = "rating %d",
    beliefsIntro = "Reality check: think about your typical trips (e.g. commuting, shopping). For each mode, how well does it fulfill your Top 3 needs?",
    beliefsScaleHint = "1 = not at all, 7 = completely",
    beliefsPickFirst = "Go back one step and pick your Top 3 needs first.",
    neverUse = "I never use / No opinion",
    mostImportantNeed = "Your most important need (Rank 1)",
    frequenciesIntro = "Think of your regular work or study route in the last 3 months. How often do you use each of the following modes to get there and back?",
    frequenciesScaleHint = "1 = never, 5 = very often",
    emovalIntro = "How do you feel about each of these transport modes?",
    emovalHint = "Slide left for negative, right for positive. Check 'No experience' if it doesn't apply.",
    negative = "negative",
    positive = "positive",
    noExperience = "No experience / no opinion",
    genStage1 = "Parsing your answers...",
    genStage2 = "Building the 19-node cognitive network...",
    genStage3 = "Imputing belief priors from population data...",
    genStage4 = "Running deliberation simulation (≈500 ODE steps)...",
    genStage5 = "Computing dissonance metrics...",
    genStage6 = "Generating your cognitive passport...",
    generatingServer = "The DYCONET model is running on the server.",
    genErrTitle = "Could not generate passport",
    genErrHelp = "Check your internet connection and that the server is reachable.",
    tryAgain = "Try again",
    useOffline = "Use sample profile (offline)",
    resultReady = "Your cognitive passport is ready",
    resultSubtitle = "We've learned what matters to you when you travel.",
    travelPersonality = "✨ YOUR TRAVEL PERSONALITY",
    readingProfile = "Reading your travel profile…",
    resultTailored = "From now on, every route suggestion is tailored to what matters to you.",
    letsBegin = "Let's begin",
    nextBtn = "Next",
    generatePassport = "Generate passport",
    continueToApp = "Continue to app",
    cognitivePassportTitle = "Cognitive passport",
    noPassportTitle = "No cognitive passport saved yet",
    noPassportSub = "Complete the profile questionnaire to generate one.",
    pdMetadata = "Metadata",
    pdMetadataSub = "Topology + identity",
    pdProfile = "Profile — your inputs",
    pdProfileSub = "Needs, tolerances, values",
    pdDeliberation = "Deliberation outcome",
    pdDeliberationSub = "What the ODE simulation produced",
    pdDissonance = "Dissonance triad",
    pdDissonanceSub = "Internal conflict diagnostics",
    pdRouting = "Routing parameters",
    pdRoutingSub = "Use these to weight routes downstream",
    pdXai = "Explanation (XAI)",
    pdXaiSub = "Why the model made this choice",
    pdAgent = "Agent profile (demographics)",
    pdSpatial = "Spatial context",
    pdSpatialSub = "Location-derived signals",
    pdTopNeeds = "Top needs ranking",
    pdRawJson = "Raw JSON",
    pdRawJsonSub = "The complete passport, exactly as the server returned it",
    needLabels = mapOf(
        "comfort_physical" to "Travel comfort",
        "reliable" to "Reliability",
        "flex" to "Flexibility",
        "cost" to "Cost",
        "safety_crime" to "Personal security",
        "health_activity" to "Physical activity",
        "time" to "Time saving",
        "health_infection" to "Health protection",
        "crowding" to "Privacy / space",
        "safety_accident" to "Traffic safety",
        "env" to "Eco-friendliness",
    ),
    needHelps = mapOf(
        "comfort_physical" to "Comfortable seats, cleanliness, pleasant temperature, quiet",
        "reliable" to "Punctuality, predictability, no cancellations",
        "flex" to "Spontaneous departures, independence from schedules",
        "cost" to "Low ticket prices, low maintenance, low fuel costs",
        "safety_crime" to "Protection from harassment or crime, feeling safe at night",
        "health_activity" to "Active transport, fitness, fresh air",
        "time" to "Fastest route, short travel time, no traffic jams",
        "health_infection" to "Low infection risk, hygiene, virus-free",
        "crowding" to "No crowding, personal space, distance from others",
        "safety_accident" to "Protection from accidents, safe technology, safe driving",
        "env" to "Low CO2 emissions, climate protection, clean air",
    ),
    onbModeLabels = mapOf(
        "walk" to "Walking",
        "bike" to "Bicycle / E-Bike",
        "pt" to "Public Transport (Bus / Tram)",
        "car" to "Car (Driver)",
    ),
    modeLabels = mapOf(
        "bike" to "Bike", "car" to "Car", "foot" to "Walk", "walk" to "Walk", "pt" to "Public transport",
    ),
    valueLabels = mapOf(
        "physical_activity" to "Active",
        "cost_saving" to "Saves money",
        "pro_environment" to "Eco",
        "speed" to "Fast",
        "comfort" to "Comfort",
        "autonomy" to "Freedom",
        "safety" to "Safety",
        "privacy" to "Privacy",
        "reliable" to "Reliable",
        "hedonism" to "Enjoyment",
    ),
)

// ---------------------------------------------------------------------
//  German (informal "du", aimed at a Magdeburg student audience)
// ---------------------------------------------------------------------
val DeStrings = Strings(
    back = "Zurück",
    cancel = "Abbrechen",
    splashTagline = "Smarte Mobilität, personalisiert",
    signupTagline = "Personalisierte, smarte Routen für Magdeburg",
    accessCode = "Zugangscode",
    getStarted = "Los geht's",
    noCodePrefix = "Noch keinen Code? ",
    registerHere = "Jetzt registrieren",
    goodMorning = "Guten Morgen",
    goodAfternoon = "Guten Tag",
    goodEvening = "Guten Abend",
    whereHeaded = "Wohin geht's heute?",
    whereTo = "Wohin?",
    smart = "Smart",
    savedRecent = "GESPEICHERT & ZULETZT",
    personalizedRouting = "Personalisierte Routen",
    rankedByPassport = "Sortiert nach deinem kognitiven Pass",
    searchPlaceMd = "Ort in Magdeburg suchen",
    popularInMd = "BELIEBT IN MAGDEBURG",
    searching = "Suche…",
    noPlacesFound = "Keine Orte in Magdeburg für \"%s\" gefunden.",
    savedHome = "Zuhause",
    savedCampus = "Campus",
    yourLocation = "Dein Standort",
    aiRecommendation = "KI-EMPFEHLUNG",
    chooseHowToGo = "WÄHLE DEINEN WEG",
    aiPick = "KI-TIPP",
    match = "Match",
    analyzing = "Analysiere Verkehr, Wetter & deinen Pass…",
    start = "Start",
    bestMatch = "%s ist deine beste Wahl",
    topsRanking = "Ganz oben in deinem Ranking — stark bei %s für dein Profil.",
    rankedHighest = "Am höchsten bewertet für deinen kognitiven Pass.",
    bestForNow = "%s — am besten für jetzt",
    directionsTitle = "Wegbeschreibung",
    openInMaps = "In Google Maps öffnen",
    settings = "Einstellungen",
    bikeLeaningProfile = "Fahrrad-orientiertes Profil",
    generalSection = "ALLGEMEIN",
    language = "Sprache",
    languageSub = "App-Sprache",
    routingPreferences = "ROUTING-EINSTELLUNGEN",
    prefEcoTitle = "Umweltfreundliche Routen bevorzugen",
    prefEcoSub = "Emissionsarme Verkehrsmittel bevorzugen",
    prefUnlitTitle = "Unbeleuchtete Wege nachts meiden",
    prefUnlitSub = "Sicherere Routen nach Einbruch der Dunkelheit",
    prefLiveTitle = "Live-Verkehr & Wetter nutzen",
    prefLiveSub = "Empfehlungen in Echtzeit anpassen",
    profileSection = "PROFIL",
    recreateProfile = "Profil neu erstellen",
    recreateProfileSub = "Onboarding wiederholen, um deinen kognitiven Pass neu zu erstellen",
    resetRecreate = "Zurücksetzen & neu erstellen",
    aboutSection = "ÜBER",
    aboutBlurb = "Personalisierte urbane Mobilität für Magdeburg — Routen sortiert nach deinem kognitiven Pass und Live-Stadtdaten.",
    resetDialogTitle = "Profil zurücksetzen?",
    resetDialogBody = "Das löscht deinen kognitiven Pass und startet die Onboarding-Fragen erneut, um ihn neu zu erstellen.",
    reset = "Zurücksetzen",
    stepWelcome = "Willkommen",
    stepNeeds = "Deine Mobilitätsbedürfnisse",
    stepPriorities = "Deine Top-3-Prioritäten",
    stepBeliefs = "Eignung der Verkehrsmittel",
    stepFrequencies = "Wie du unterwegs bist",
    stepEmoval = "Wie sich Verkehrsmittel anfühlen",
    stepGenerating = "Wir bauen deinen Pass",
    stepResult = "Dein kognitiver Pass",
    stepXofY = "Schritt %d von %d",
    welcomeHeadline = "Lernen wir deinen Mobilitätstyp kennen",
    welcomeBody = "Ein kurzer Fragebogen in 5 Teilen. Dauert etwa 4 Minuten. Danach erstellen wir deinen persönlichen kognitiven Pass — eine Karte davon, wie du verschiedene Mobilitätsbedürfnisse gewichtest.",
    welcomeInfo1 = "Bewerte 11 Mobilitätsbedürfnisse (1–7)",
    welcomeInfo2 = "Wähle deine Top-3-Prioritäten",
    welcomeInfo3 = "Bewerte, wie gut Verkehrsmittel zu dir passen",
    welcomeInfo4 = "Sag uns, wie oft du jedes Verkehrsmittel nutzt",
    welcomeInfo5 = "Teile, wie sich jedes Verkehrsmittel anfühlt",
    needsIntro = "Wie wichtig ist dir jedes davon persönlich, wenn du ein Verkehrsmittel wählst?",
    needsScaleHint = "1 = überhaupt nicht wichtig, 7 = extrem wichtig",
    prioritiesIntro = "Man kann nicht alles auf einmal haben. Wähle aus der Liste die 3 wichtigsten Bedürfnisse für deine Verkehrsmittelwahl – der Reihe nach.",
    prioritiesTapHint = "Tippe unten auf ein Bedürfnis, um es zur Pyramide hinzuzufügen:",
    empty = "leer",
    ratingLabel = "Wert %d",
    beliefsIntro = "Realitäts-Check: Denk an deine typischen Wege (z. B. Pendeln, Einkaufen). Wie gut erfüllt jedes Verkehrsmittel deine Top-3-Bedürfnisse?",
    beliefsScaleHint = "1 = überhaupt nicht, 7 = vollständig",
    beliefsPickFirst = "Geh einen Schritt zurück und wähle zuerst deine Top-3-Bedürfnisse.",
    neverUse = "Nutze ich nie / keine Meinung",
    mostImportantNeed = "Dein wichtigstes Bedürfnis (Rang 1)",
    frequenciesIntro = "Denk an deinen regelmäßigen Weg zur Arbeit oder Uni in den letzten 3 Monaten. Wie oft nutzt du die folgenden Verkehrsmittel für Hin- und Rückweg?",
    frequenciesScaleHint = "1 = nie, 5 = sehr oft",
    emovalIntro = "Wie fühlst du dich bei jedem dieser Verkehrsmittel?",
    emovalHint = "Nach links für negativ, nach rechts für positiv. „Keine Erfahrung\" ankreuzen, wenn es nicht zutrifft.",
    negative = "negativ",
    positive = "positiv",
    noExperience = "Keine Erfahrung / keine Meinung",
    genStage1 = "Analysiere deine Antworten…",
    genStage2 = "Baue das kognitive Netz mit 19 Knoten…",
    genStage3 = "Schätze Glaubens-Priors aus Bevölkerungsdaten…",
    genStage4 = "Starte Deliberations-Simulation (≈500 ODE-Schritte)…",
    genStage5 = "Berechne Dissonanz-Metriken…",
    genStage6 = "Erstelle deinen kognitiven Pass…",
    generatingServer = "Das DYCONET-Modell läuft auf dem Server.",
    genErrTitle = "Pass konnte nicht erstellt werden",
    genErrHelp = "Prüfe deine Internetverbindung und ob der Server erreichbar ist.",
    tryAgain = "Erneut versuchen",
    useOffline = "Beispielprofil verwenden (offline)",
    resultReady = "Dein kognitiver Pass ist fertig",
    resultSubtitle = "Wir wissen jetzt, was dir beim Reisen wichtig ist.",
    travelPersonality = "✨ DEINE REISE-PERSÖNLICHKEIT",
    readingProfile = "Lese dein Reiseprofil…",
    resultTailored = "Ab jetzt ist jede Routenempfehlung auf das zugeschnitten, was dir wichtig ist.",
    letsBegin = "Los geht's",
    nextBtn = "Weiter",
    generatePassport = "Pass erstellen",
    continueToApp = "Weiter zur App",
    cognitivePassportTitle = "Kognitiver Pass",
    noPassportTitle = "Noch kein kognitiver Pass gespeichert",
    noPassportSub = "Schließe den Profil-Fragebogen ab, um einen zu erstellen.",
    pdMetadata = "Metadaten",
    pdMetadataSub = "Topologie + Identität",
    pdProfile = "Profil — deine Eingaben",
    pdProfileSub = "Bedürfnisse, Toleranzen, Werte",
    pdDeliberation = "Deliberations-Ergebnis",
    pdDeliberationSub = "Was die ODE-Simulation erzeugt hat",
    pdDissonance = "Dissonanz-Triade",
    pdDissonanceSub = "Diagnostik innerer Konflikte",
    pdRouting = "Routing-Parameter",
    pdRoutingSub = "Damit werden Routen gewichtet",
    pdXai = "Erklärung (XAI)",
    pdXaiSub = "Warum das Modell so entschieden hat",
    pdAgent = "Agentenprofil (Demografie)",
    pdSpatial = "Räumlicher Kontext",
    pdSpatialSub = "Aus dem Standort abgeleitete Signale",
    pdTopNeeds = "Top-Bedürfnisse-Ranking",
    pdRawJson = "Roh-JSON",
    pdRawJsonSub = "Der vollständige Pass, genau wie vom Server geliefert",
    needLabels = mapOf(
        "comfort_physical" to "Reisekomfort",
        "reliable" to "Verlässlichkeit",
        "flex" to "Flexibilität",
        "cost" to "Kosten",
        "safety_crime" to "Persönliche Sicherheit",
        "health_activity" to "Körperliche Aktivität",
        "time" to "Zeitersparnis",
        "health_infection" to "Gesundheitsschutz",
        "crowding" to "Privatsphäre / Platz",
        "safety_accident" to "Verkehrssicherheit",
        "env" to "Umweltfreundlichkeit",
    ),
    needHelps = mapOf(
        "comfort_physical" to "Bequeme Sitze, Sauberkeit, angenehme Temperatur, Ruhe",
        "reliable" to "Pünktlichkeit, Planbarkeit, keine Ausfälle",
        "flex" to "Spontane Abfahrten, Unabhängigkeit von Fahrplänen",
        "cost" to "Niedrige Ticketpreise, geringe Wartung, niedrige Spritkosten",
        "safety_crime" to "Schutz vor Belästigung oder Kriminalität, sich nachts sicher fühlen",
        "health_activity" to "Aktive Fortbewegung, Fitness, frische Luft",
        "time" to "Schnellste Route, kurze Reisezeit, kein Stau",
        "health_infection" to "Geringes Ansteckungsrisiko, Hygiene, virenfrei",
        "crowding" to "Kein Gedränge, persönlicher Raum, Abstand zu anderen",
        "safety_accident" to "Schutz vor Unfällen, sichere Technik, sichere Fahrweise",
        "env" to "Niedrige CO2-Emissionen, Klimaschutz, saubere Luft",
    ),
    onbModeLabels = mapOf(
        "walk" to "Zu Fuß",
        "bike" to "Fahrrad / E-Bike",
        "pt" to "ÖPNV (Bus / Straßenbahn)",
        "car" to "Auto (selbst fahren)",
    ),
    modeLabels = mapOf(
        "bike" to "Fahrrad", "car" to "Auto", "foot" to "Zu Fuß", "walk" to "Zu Fuß", "pt" to "ÖPNV",
    ),
    valueLabels = mapOf(
        "physical_activity" to "Aktiv",
        "cost_saving" to "Spart Geld",
        "pro_environment" to "Öko",
        "speed" to "Schnell",
        "comfort" to "Komfort",
        "autonomy" to "Freiheit",
        "safety" to "Sicherheit",
        "privacy" to "Privatsphäre",
        "reliable" to "Verlässlich",
        "hedonism" to "Genuss",
    ),
)
